spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.security: DEBUG
    com.invy.backend: DEBUG

app:
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth2/redirect